version: '3.8'

services:
  backend:
    image: ${REGISTRY:-ghcr.io}/${NAMESPACE:-printfarmhq}/printfarmhq-backend:${VERSION:-latest}
    container_name: printfarmhq-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SUPERADMIN_EMAIL=${SUPERADMIN_EMAIL}
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
      - SUPERADMIN_NAME=${SUPERADMIN_NAME}
    env_file: 
      - backend/.env
    networks:
      - printfarmhq-network

  frontend:
    image: ${REGISTRY:-ghcr.io}/${NAMESPACE:-printfarmhq}/printfarmhq-frontend:${VERSION:-latest}
    container_name: printfarmhq-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file: 
      - frontend/.env.local
    networks:
      - printfarmhq-network

networks:
  printfarmhq-network:
    driver: bridge