services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REGISTRY: ${REGISTRY:-ghcr.io}
        NAMESPACE: ${NAMESPACE:-jnardiello}
        BASE_TAG: ${VERSION:-latest}
    image: ${REGISTRY:-ghcr.io}/${NAMESPACE:-jnardiello}/printfarmhq:backend-${VERSION:-latest}
    container_name: printfarmhq-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # No environment variables needed - using database-based configuration
    networks:
      - printfarmhq-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REGISTRY: ${REGISTRY:-ghcr.io}
        NAMESPACE: ${NAMESPACE:-jnardiello}
        BASE_TAG: ${VERSION:-latest}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        DOCKER_ENV: "true"
    image: ${REGISTRY:-ghcr.io}/${NAMESPACE:-jnardiello}/printfarmhq:frontend-${VERSION:-latest}
    container_name: printfarmhq-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - DOCKER_ENV=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - printfarmhq-network

networks:
  printfarmhq-network:
    driver: bridge