# Local development override - builds images locally
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REGISTRY: ${REGISTRY:-ghcr.io}
        NAMESPACE: ${NAMESPACE:-printfarmhq}
        BASE_TAG: ${VERSION:-latest}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REGISTRY: ${REGISTRY:-ghcr.io}
        NAMESPACE: ${NAMESPACE:-printfarmhq}
        BASE_TAG: ${VERSION:-latest}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        DOCKER_ENV: "true"