name: Test Suite

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run all tests in Docker
      run: make test-ci

    - name: Upload backend test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: backend-test-results
        path: |
          backend/test-results/
          backend/htmlcov/
          backend/coverage.xml

    - name: Upload frontend test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-test-results
        path: |
          frontend/test-results/
          frontend/playwright-report/

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: '**/test-results/*.xml'
        reporter: java-junit

    - name: Coverage Report
      uses: codecov/codecov-action@v4
      with:
        files: ./backend/coverage.xml
        fail_ci_if_error: true